#!/bin/sh

# 作为OpenWrt热插拔iface钩子脚本，在网口状态变化时联动MPTCP配置
## 接口上线/更新时，按接口配置是否开启 multipath 来触发 MPTCP 的配置重载
## 接口下线时，关闭该设备的 MPTCP multipath

[ "$ACTION" = ifup -o "$ACTION" = ifupdate -o "$ACTION" = ifdown -o "$ACTION" = iflink -o "$ACTION" = link-up -o "$ACTION" = link-down ] || exit 0
#[ "$ACTION" = ifupdate -a -z "$IFUPDATE_ADDRESSES" -a -z "$IFUPDATE_DATA" ] && exit 0


/etc/init.d/mptcp enabled || exit 0


if [ "$ACTION" = ifup -o "$ACTION" = ifupdate -o "$ACTION" = iflink  -o "$ACTION" = link-up ] && [ -z "$(echo $DEVICE | grep oip | grep gre)" ] && [ -n "$(uci -q get network.$INTERFACE.multipath)" ] && [ "$(uci -q get network.$INTERFACE.multipath)" != "off" ]; then
	logger -t "mptcp" "Reloading mptcp config due to $ACTION of $INTERFACE ($DEVICE)"
	/etc/init.d/mptcp reload "$DEVICE" >/dev/null || exit 0
elif [ "$ACTION" = ifdown -o "$ACTION" = link-down ]; then
	multipath $DEVICE off 2>&1 >/dev/null || exit 0
fi

