#!/bin/sh /etc/rc.common
# Copyright (C) 2018-2025 Ycarus (Yannick Chabanois) <ycarus@zugaina.org>
# Released under GPL 3. See LICENSE for the full terms.

START=99

USE_PROCD=1

EXTRA_COMMANDS="backup_send backup_get backup_list get_openvpn_key token set_vpn_ip"

. /usr/lib/unbound/iptools.sh

# 新的nftables框架
if [ -e /usr/sbin/iptables-nft ]; then
	IPTABLES="/usr/sbin/iptables-nft"
	IPTABLESRESTORE="/usr/sbin/iptables-nft-restore"
	IPTABLESSAVE="/usr/sbin/iptables-nft-save"
	IP6TABLES="/usr/sbin/ip6tables-nft"
	IP6TABLESRESTORE="/usr/sbin/ip6tables-nft-restore"
	IP6TABLESSAVE="/usr/sbin/ip6tables-nft-save"
# 传统的iptables
else
	IPTABLES="/usr/sbin/iptables"
	IPTABLESRESTORE="/usr/sbin/iptables-restore"
	IPTABLESSAVE="/usr/sbin/iptables-save"
	IP6TABLES="/usr/sbin/ip6tables"
	IP6TABLESRESTORE="/usr/sbin/ip6tables-restore"
	IP6TABLESSAVE="/usr/sbin/ip6tables-save"
fi

# 解析JSON格式的数据中的result字段
_parse_result() {
	result=$("echo $1 | jsonfilter -q -e '@.result'")
	echo $result
}

# VPS服务器的认证登录
_login() {
	local username password auth
	
	# 从配置文件/etc/config/openmptcprouter中获取用户名、密码、端口
	username="$(uci -q get openmptcprouter.${servername}.username)"		# uci get openmptcprouter.vps.username
	password="$(uci -q get openmptcprouter.${servername}.password)"		# uci get openmptcprouter.vps.password
	serverport="$(uci -q get openmptcprouter.${servername}.port)"		# uci get openmptcprouter.vps.port

	# 自动获取服务器密码，自动登录
	local serverip="$(uci -q get openmptcprouter.vps.ip)"
	# 检查服务器IP地址格式是否正确
	[ "$(valid_subnet_any "$serverip")" != "ok" ] && logger -t "OMR" "<$FUNCNAME> Unkonwn server ip: ${serverip}! " && return
	# 序列号, 以CPU序列号作为整机序列号
	[ "${serial}" == "" ] && serial=$(cat /proc/cpuinfo | grep Serial | awk '{print $3}') && logger -t "OMR" "serial: ${serial}"
	# curl -s -k -X POST https://36.133.201.26:65500/passwd?serial=0123456789
	new_password="$(curl -s -k -X POST https://${serverip}:${serverport}/passwd?serial=${serial} | jsonfilter -e '@.password')"
	# 遍历默认路由接口,触发系统路由选择不同出口网卡,这段逻辑存疑! 明明没有切换网卡的逻辑呀? 一直使用的都是默认网关对应的网口...
	if [ -z "$new_password" ]; then
		for intf in $(multipath 2>/dev/null | awk '/default/ { print $1 }'); do
			new_password="$(curl -s -k -X POST https://${serverip}:${serverport}/passwd?serial=${serial})"
			[ -n "$new_password" ] && break
		done
	fi

	# 无法获取服务器访问密码,直接return
	[ ! -n "$new_password" ] && logger -t "OMR" "<$FUNCNAME> Get server ${serverip}:${serverport} password error! " && return
	# 更新uci配置文件中的password
	if [ "$new_password" != "$password" ]; then
		logger -t "OMR" "<$FUNCNAME> new_password: ${new_password}"
		password=${new_password}
		logger -t "OMR" "<$FUNCNAME> uci -q set openmptcprouter.${servername}.password=${password}"
		uci -q set openmptcprouter.${servername}.password=${password}
	fi

	# 获取身份认证token
	if [ -z "$token" ]; then

		# 代码块中的函数, 从服务器获取token
		login_on_server() {
			[ -n "$token" ] && return
			server=$1
			
			# submodules/feeds/6.6/packages/net/unbound/files/iptools.sh -> valid_subnet6()
			valid_ip6=$(valid_subnet6 $server)
			# IPv6
			if [ "$valid_ip6" = "ok" ]; then
				auth=`curl --max-time 10 -s -k -H "accept: application/json" -H "Content-Type: application/x-www-form-urlencoded" -X POST -d 'username='$username'&password='$password https://[$server]:$serverport/token`
			# IPv4
			else
				auth=`curl --max-time 10 -s -k -H "accept: application/json" -H "Content-Type: application/x-www-form-urlencoded" -X POST -d 'username='$username'&password='$password https://$server:$serverport/token`
			fi

			# auth为空，认证失败,使用其他接口重新尝试
			if [ -z "$auth" ]; then
				for intf in $(multipath 2>/dev/null | awk '/default/ { print $1 }'); do
					if [ "$valid_ip6" = "ok" ]; then
						auth=`curl --max-time 10 -s -k --interface $intf -H "accept: application/json" -H "Content-Type: application/x-www-form-urlencoded" -X POST -d 'username='$username'&password='$password https://[$server]:$serverport/token`
					else
						auth=`curl --max-time 10 -s -k --interface $intf -H "accept: application/json" -H "Content-Type: application/x-www-form-urlencoded" -X POST -d 'username='$username'&password='$password https://$server:$serverport/token`
					fi
					[ -n "$auth" ] && break
				done
			fi

			# 认证成功，解析获取token字段，保存到配置文件/etc/config/openmptcprouter中
			[ -n "$auth" ] && {
				token="$(echo "$auth" | jsonfilter -q -e '@.access_token')"
				uci -q set openmptcprouter.${servername}.token="$token"
			}
		}

		# 从文件/etc/config/openmptcprouter中加载配置到环境变量
		config_load openmptcprouter
		# 遍历所有的VPS服务器, 对/etc/config/openmptcprouter中的vps section中的list ip中的每个ip都执行login_on_server
		config_list_foreach ${servername} ip login_on_server
	fi
}

# VPS服务器的ping连通性状态检查
_ping_server() {
	server="$1"
	# 发送3个ICMP回显请求包,总超时时间为3秒,设置ICMP包的TOS字段为184,标记ping包为高优先级
	ret=$(ping -c 3 -w 3 -Q 184 $server 2>&1) && echo "$ret" | grep -sq "bytes from" && return
	false
}

# 发起http GET请求，获取JSON格式的响应数据
_get_json() {
	local route result
	# 请求的API URL
	route=$1
	# 没有token,需要先登录认证获取token
	[ -z "$token" ] && _login
	# 发起http请求，获取JSON格式的响应数据
	[ -n "$token" ] && {
		#resolve="$(resolveip -t 5 $server)"
		# http请求
		valid_ip6=$(valid_subnet6 $server)
		if [ "$valid_ip6" = "ok" ]; then
			logger -t "OMR" "<$FUNCNAME> curl https://[$server]:$serverport/$route"
			result=`curl --max-time 10 -s -k -H "accept: application/json" -H "Authorization: Bearer $token" https://[$server]:$serverport/$route`
		else
			logger -t "OMR" "<$FUNCNAME> curl https://$server:$serverport/$route"
			result=`curl --max-time 10 -s -k -H "accept: application/json" -H "Authorization: Bearer $token" https://$server:$serverport/$route`
		fi
		# 获取http响应失败，使用其它接口重试
		if [ -z "$result" ]; then
			for intf in $(multipath 2>/dev/null | awk '/default/ { print $1 }'); do
				if [ "$valid_ip6" = "ok" ]; then
					result=`curl --max-time 10 -s -k --interface $intf -H "accept: application/json" -H "Authorization: Bearer $token" https://[$server]:$serverport/$route`
				else
					result=`curl --max-time 10 -s -k --interface $intf -H "accept: application/json" -H "Authorization: Bearer $token" https://$server:$serverport/$route`
				fi
				[ -n "$result" ] && break
			done
		fi
		# 获取http响应失败
		if [ "$(echo $result | grep 'Could not validate credentials')" ]; then
			result=''
		fi
		# 获取http响应成功
		echo $result
	} || {
		echo ''
	}
}

# 设置JSON格式的请求体，并发起http POST请求
_set_json() {
	local route result settings
	# 请求URL
	route=$1
	settings="$2"
	# 没有token,需要先登录认证获取token
	[ -z "$token" ] && _login
	[ -n "$token" ] && {
		#resolve="$(resolveip -t 5 $server)"
		valid_ip6=$(valid_subnet6 $server)
		if [ "$valid_ip6" = "ok" ]; then
			logger -t "OMR" "curl post https://[$server]:$serverport/$route ${settings}"
			result=`curl --max-time 10 -s -k -H "Authorization: Bearer $token" -H "Content-Type: application/json" -X POST -d "$settings" https://[$server]:$serverport/$route`
		else
			logger -t "OMR" "curl post https://$server:$serverport/$route ${settings}"
			result=`curl --max-time 10 -s -k -H "Authorization: Bearer $token" -H "Content-Type: application/json" -X POST -d "$settings" https://$server:$serverport/$route`
		fi
		if [ -z "$result" ]; then
			for intf in $(multipath 2>/dev/null | awk '/default/ { print $1 }'); do
				if [ "$valid_ip6" = "ok" ]; then
					logger -t "OMR" "curl post https://[$server]:$serverport/$route ${settings}"
					result=`curl --max-time 10 -s -k --interface $intf -H "Authorization: Bearer $token" -H "Content-Type: application/json" -X POST -d "$settings" https://[$server]:$serverport/$route`
				else
					logger -t "OMR" "curl post https://$server:$serverport/$route ${settings}"
					result=`curl --max-time 10 -s -k --interface $intf -H "Authorization: Bearer $token" -H "Content-Type: application/json" -X POST -d "$settings" https://$server:$serverport/$route`
				fi
				[ -n "$result" ] && break
			done
		fi
		if [ "$(echo $result | grep 'Could not validate credentials')" ]; then
			result=''
		fi
		echo $result
	} || {
		echo ''
	}
}

# 当你在路由器上更新了 OpenVPN 端口或加密算法，本地对比不一致时， _set_openvpn_vps 会把这些设置同步到 VPS
# 当 VPS 返回的客户端密钥与本地不一致时， _set_openvpn_vps 会打 get_config 标记。随后通过显式调用 get_openvpn_key <servername> ，从 VPS 拉取并写入客户端密钥/证书/CA 文件
_set_openvpn_vps() {

	local enabled="$(uci -q get openvpn.omr.enabled)"
	
	# openvpn 未启用, 则启用之
	[ "$enabled" != "1" ] && { 
		logger -t "OMR" "<$FUNCNAME> OpenVPN disabled! re-enable now..."
		uci -q set openvpn.omr.enabled=1 && uci commit openvpn
		# return
	}

	[ -n "$(uci -q get openvpn.omr2)" ] && uci delete openvpn.omr2
	[ -n "$(uci -q get openvpn.omr3)" ] && uci delete openvpn.omr3
	[ -n "$(uci -q get openvpn.omr4)" ] && uci delete openvpn.omr4
	[ -n "$(uci -q changes openvpn)" ] && uci commit openvpn

	local port="$(uci -q get openvpn.omr.port)"						# 服务器端口 65301
	local cipher="$(uci -q get openvpn.omr.cipher)"					# 加密算法
	local key="$(base64 /etc/luci-uploads/client.key | tr -d "\n")"	# 客户端秘钥

	# 发起http请求，根据序列号从VPS检索对应的OpenVPN配置
	[ -z "$vps_config" ] && vps_config=$(_get_json "config?serial=${serial}")
	[ -z "$vps_config" ] && logger -t "OMR" "<$FUNCNAME> vps_config is empty! return now..." && return
	local current_key="$(echo "$vps_config" | jsonfilter -q -e '@.openvpn.client_key')"
	local current_port="$(echo "$vps_config" | jsonfilter -q -e '@.openvpn.port')"
	local current_cipher="$(echo "$vps_config" | jsonfilter -q -e '@.openvpn.cipher')"

	# 表示更新了OpenVPN的秘钥,提示本地需要拉取最新客户端配置
	if [ "$current_key" != "$key" ]; then
		logger -t "OMR" "<$FUNCNAME> OpenVPN key changed"
		uci -q set openmptcprouter.${servername}.get_config="1"
	fi

	logger -t "OMR" "<$FUNCNAME> port:${port}"
	logger -t "OMR" "<$FUNCNAME> cipher:${cipher}"
	# logger -t "OMR" "<$FUNCNAME> key:${key}"

	# 更新了OpenVPN的端口或加密算法
	if [ "$current_port" != "$port" ] || [ "$current_cipher" != "$cipher" ]; then
		local settings='{"port": '$port', "cipher": "'$cipher'"}'
		echo $(_set_json "openvpn" "$settings")
	else
		echo 1
	fi
}

# 外部调用，从VPN获取OpenVPN的密钥，并重启OpenVPN服务
get_openvpn_key() {
	servername=$2
	[ -z "$vps_config" ] && vps_config=$(_get_json "config?serial=${serial}")
	[ -z "$vps_config" ] && return
	openvpn_client_key="$(echo "$vps_config" | jsonfilter -q -e '@.openvpn.client_key')"
	[ -n "$openvpn_client_key" ] && {
		echo $openvpn_client_key | base64 -d > /etc/luci-uploads/client.key
	}
	openvpn_client_crt="$(echo "$vps_config" | jsonfilter -q -e '@.openvpn.client_crt')"
	[ -n "$openvpn_client_crt" ] && {
		echo $openvpn_client_crt | base64 -d > /etc/luci-uploads/client.crt
	}
	openvpn_client_ca="$(echo "$vps_config" | jsonfilter -q -e '@.openvpn.client_ca')"
	[ -n "$openvpn_client_ca" ] && {
		echo $openvpn_client_ca | base64 -d > /etc/luci-uploads/ca.crt
	}
	[ -n "$openvpn_client_key" ] && [ -n "$openvpn_client_crt" ] && [ -n "$openvpn_client_ca" ] && {
		[ "$(uci -q get openvpn.omr.enabled)" ] && /etc/init.d/openvpn restart
	}
}

# 从VPS获取配置，同步到本地
_get_vps_config() {

	# 首先获取VPS配置
	# 如果配置为空则返回
	# 然后检查配置的最后修改时间，如果VPS配置比本地新，则调用 _set_config_from_vps 更新本地配置
	[ -z "$vps_config" ] && vps_config=$(_get_json "config?serial=${serial}")
	[ -z "$vps_config" ] && return
	vps_lastchange="$(echo "$vps_config" | jsonfilter -q -e '@.vps.lastchange')"
	if [ -n "$(uci -q get openmptcprouter.${servername}.lastchange)" ] && [ -n "$vps_lastchange" ] && [ "$vps_lastchange" -gt "$(uci -q get openmptcprouter.${servername}.lastchange)" ]; then
		_set_config_from_vps
	fi

	# VPS系统信息同步: 内核版本、机器类型和OpenMPTCRouter版本信息
	vpsinternet="$(echo "$vps_config" | jsonfilter -q -e '@.network.internet')"
	if [ "$vpsinternet" = "false" ] && [ "$(uci -q get openmptcprouter.settings.external_check)" != "0" ]; then
		uci -q batch <<-EOF >/dev/null
			set openmptcprouter.settings.external_check='0'
			commit openmptcprouter
		EOF
	fi

	vps_kernel="$(echo "$vps_config" | jsonfilter -q -e '@.vps.kernel')"
	vps_machine="$(echo "$vps_config" | jsonfilter -q -e '@.vps.machine')"
	vps_omr_version="$(echo "$vps_config" | jsonfilter -q -e '@.vps.omr_version')"
	uci -q batch <<-EOF >/dev/null
		set openmptcprouter.${servername}.kernel=$vps_kernel
		set openmptcprouter.${servername}.machine=$vps_machine
		set openmptcprouter.${servername}.omr_version=$vps_omr_version
	EOF

	# VPN配置同步
	vpn="$(uci -q get openmptcprouter.settings.vpn)"

	# 解析和处理VPS的IP地址，允许以域名方式指定服务器IP
	vpsip="$(uci -q get openmptcprouter.${servername}.ip | awk '{print $1}')"
	ipresolve="$(resolveip -t 5 -4 $vpsip | head -n 1)"
	if [ -n "$ipresolve" ]; then
		vpsip="$ipresolve"
	else
		ip6resolve="$(resolveip -t 5 -6 $vpsip | head -n 1)"
		[ -n "$ip6resolve" ] && vpsip="$ip6resolve"
	fi

	# openvpn配置
	if [ -n "$(uci -q get openvpn.omr)" ] && [ "$(uci -q get openvpn.omr.remote)" != "127.0.0.1" ] && [ -z "$(uci -q get openvpn.omr.remote | grep $vpsip)" ] && [ "$(uci -q get openmptcprouter.settings.ha)" != "1" ]; then
		uci -q batch <<-EOF >/dev/null
			delete openvpn.omr.remote
			add_list openvpn.omr.remote="$vpsip"
			commit openvpn
		EOF
		if [ "$(uci -q get openvpn.omr.enabled)" = "1" ]; then
			logger -t "OMR" "Restart OpenVPN..."
			/etc/init.d/openvpn restart
		fi
	fi
}

# 从VPS同步端口重定向配置
_set_redirect_ports_from_vps() {

	logger -t "OMR" "<$FUNCNAME>..."

	redirect_ports=$1
	[ -z "$vps_config" ] && vps_config=$(_get_json "config?serial=${serial}")
	[ -z "$vps_config" ] && return
	redirect_ports_current="$(echo "$vps_config" | jsonfilter -q -e '@.shorewall.redirect_ports')"
	[ "$redirect_ports" = "1" ] && redirect_ports_request="enable"
	[ "$redirect_ports" = "0" ] && redirect_ports_request="disable"

	logger -t "OMR" "<$FUNCNAME> redirect_ports_request=${redirect_ports_request}"
	logger -t "OMR" "<$FUNCNAME> redirect_ports=${redirect_ports_current}"

	if [ "$redirect_ports_request" != "$redirect_ports_current" ]; then
		settings='{"redirect_ports": "'$redirect_ports_request'"}'
		echo $(_set_json "shorewall" "$settings")
	else
		echo 1
	fi

}

# 和VPS同步MPTCP配置
_set_mptcp_vps() {

	logger -t "OMR" "<$FUNCNAME>..."

	local settings
	[ -z "$vps_config" ] && vps_config=$(_get_json "config?serial=${serial}")
	[ -z "$vps_config" ] && logger -t "OMR" "<$FUNCNAME> vps_config is empty! return now..." && return
	mptcp_enabled_current="$(echo "$vps_config" | jsonfilter -q -e '@.mptcp.enabled')"
	checksum_current="$(echo "$vps_config" | jsonfilter -q -e '@.mptcp.checksum')"
	path_manager_current="$(echo "$vps_config" | jsonfilter -q -e '@.mptcp.path_manager')"
	scheduler_current="$(echo "$vps_config" | jsonfilter -q -e '@.mptcp.scheduler')"
	syn_retries_current="$(echo "$vps_config" | jsonfilter -q -e '@.mptcp.syn_retries')"
	congestion_control_current="$(echo "$vps_config" | jsonfilter -q -e '@.network.congestion_control')"
	mptcp_version_current="$(echo "$vps_config" | jsonfilter -q -e '@.mptcp.version')"
	mptcp_enabled="$(uci -q get network.globals.multipath)"
	if [ "$mptcp_enabled" = "disable" ]; then
		mptcp_enabled="0"
	else
		mptcp_enabled="1"
	fi
	checksum="$(uci -q get network.globals.mptcp_checksum)"
	path_manager="$(uci -q get network.globals.mptcp_path_manager)"
	scheduler="$(uci -q get network.globals.mptcp_scheduler)"
	syn_retries="$(uci -q get network.globals.mptcp_syn_retries)"
	congestion="$(uci -q get network.globals.congestion)"
	mptcp_version="$(uci -q get network.globals.mptcp_version)"
	[ -z "$mptcp_version" ] && mptcp_version="0"
	[ ! -f /proc/sys/net/mptcp/mptcp_enabled ] && mptcp_version="1"
	[ -z "$congestion" ] && congestion="bbr"

	logger -t "OMR" "<$FUNCNAME> mptcp_enabled=${mptcp_enabled} checksum=${checksum} path_manager=${path_manager}" \
	"scheduler=${scheduler} syn_retries=${syn_retries} congestion=${congestion} mptcp_version=${mptcp_version}"

	if [ "$mptcp_enabled_current" != "$mptcp_enabled" ] \
	|| [ "$checksum_current" != "$checksum" ] \
	|| ([ "$path_manager_current" != "" ] && [ "$path_manager_current" != "$path_manager" ]) \
	|| ([ "$scheduler_current" != "" ] && [ "$scheduler_current" != "$scheduler" ]) \
	|| ([ "$syn_retries_current" != "" ] && [ "$syn_retries_current" != "$syn_retries" ]) \
	|| [ "$congestion_control_current" != "$congestion" ] \
	|| [ "$mptcp_version_current" != "$mptcp_version" ]; then
		settings='{"enabled" : "'$mptcp_enabled'", "checksum": "'$checksum'","path_manager": "'$path_manager'","scheduler": "'$scheduler'","syn_retries": "'$syn_retries'","congestion_control": "'$congestion'","version": "'$mptcp_version'"}'
		logger -t "OMR" "<$FUNCNAME> set vps mptcp: ${settings}"
		echo $(_set_json "mptcp" "$settings")
	else
		echo 1
	fi
}

# 设置默认VPN
_set_vpn_vps() {

	[ -z "$vps_config" ] && vps_config=$(_get_json "config?serial=${serial}")
	[ -z "$vps_config" ] && logger -t "OMR" "<$FUNCNAME> vps_config is empty! return now..." && return
	vpn_current="$(echo "$vps_config" | jsonfilter -q -e '@.vpn.current')"
	vpn="$(uci -q get openmptcprouter.settings.vpn)"

	logger -t "OMR" "<$FUNCNAME> vpn:${vpn}"
	
	if [ "$vpn_current" != "$vpn" ]; then
		local settings='{"vpn" : "'$vpn'"}'
		logger -t "OMR" "<$FUNCNAME> set vps vpn change from ${vpn_current} to ${vpn}"
		echo $(_set_json "vpn" "$settings")
	else
		echo 1
	fi
}

# 从VPS获取默认代理设置
# _set_proxy_vps() {

# 	logger -t "OMR" "<$FUNCNAME>..."

# 	local settings
# 	[ -z "$vps_config" ] && vps_config=$(_get_json "config?serial=${serial}")
# 	[ -z "$vps_config" ] && logger -t "OMR" "<$FUNCNAME> vps_config is empty! return now..." && return
# 	proxy_current="$(echo "$vps_config" | jsonfilter -q -e '@.proxy.current')"
# 	proxy="$(uci -q get openmptcprouter.settings.proxy)"

# 	logger -t "OMR" "<$FUNCNAME> proxy:${proxy}"

# 	if [ "$proxy_current" != "$proxy" ]; then
# 		settings='{"proxy" : "'$proxy'"}'
# 		logger -t "OMR" "<$FUNCNAME> set VPS proxy:${proxy}"
# 		echo $(_set_json "proxy" "$settings")
# 	else
# 		echo 1
# 	fi
# }

# 获取网络接口的公网IP地址
_get_local_wan_ip() {
	# uci -q get openmptcprouter.wan1.publicip
	wanip="$(uci -q get openmptcprouter.$1.publicip)"
	[ -n "$wanip" ] && {
		[ -z "$wanips" ] && wanips=$wanip || wanips="$wanips"'\n'"$wanip"
	}

	# logger -t "OMR" "<$FUNCNAME> interface:$1 wanip:${wanip}"
}

# 设备和VPS之间同步WAN口IP地址配置
_set_wan_ip() {

	[ -z "$vps_config" ] && vps_config=$(_get_json "config?serial=${serial}")
	[ -z "$vps_config" ] && logger -t "OMR" "<$FUNCNAME> No config" && return

	wanip_current="$(echo "$vps_config" | jsonfilter -q -e '@.wan.ips')"

	logger -t "OMR" "<$FUNCNAME> wanips:${wanips}"

	# wan口IP有变换，重新同步到服务器
	if [ -n "$wanips" ] && [ "$wanip_current" != "$wanips" ]; then
		local settings='{"ips" : "'$wanips'"}'
		logger -t "OMR" "<$FUNCNAME> post wanips to vps"
		result=$(_set_json "wan" "$settings")
	fi
}

# 设备和VPS之间同步SIP ALG（应用层网关）的配置，以支持SIP协议通信
_set_sipalg() {
	sipalg="$(uci -q get openmptcprouter.settings.sipalg)"
	if [ "$sipalg" = "1" ]; then
		sipalg="true"
	else
		sipalg="false"
	fi

	logger -t "OMR" "<$FUNCNAME> sipalg:${sipalg}"

	local settings='{"enable" : "'$sipalg'"}'
	result=$(_set_json "sipalg" "$settings")
}

_vps_firewall_redirect_port() {
	local src proto src_dport section
	section=$1
	config_get src $1 src
	config_get proto $1 proto "tcp udp"
	config_get src_dport $1 src_dport
	config_get family $1 family "ipv4"
	config_get enabled $1 enabled "1"
	config_get src_dip $1 src_dip
	config_get dest_ip $1 dest_ip
	config_get dest_port $1 dest_port
	config_get src_ip $1 src_ip
	config_get v2ray $1 v2ray "0"
	config_get name $1 name
	config_get dmz $1 dmz "0"
	config_get target $1 target "REDIRECT"
	[ "$target" = "MARK" ] && return
	[ "$target" = "DSCP" ] && return
	if [ -z "$src_dport" ] && [ -n "$dest_port" ]; then
		src_dport=$dest_port
	fi
	if [ "$dmz" = "1" ] && [ "$src_dport" != "2-64999" ]; then
		uci -q batch <<-EOF >/dev/null
			set firewall.${section}.src_dport='2-64999'
			commit firewall
		EOF
		src_dport='2-64999'
	fi
	[ -n "$src_dport" ] && src_dport=$(echo $src_dport | sed 's/:/-/')
	if [ -n "$src_dport" ] && [ "$(echo $src_dport | cut -d'-' -f2)" -ge "65000" ]; then
		logger -t "OMR" "You can't redirect ports >= 65000, they are needed by OpenMPTCProuter Server part"
		enabled="0"
		#uci -q delete firewall.$1
		#return
	fi

	[ "$proto" = "all" ] && proto="tcp udp"
	[ "$proto" = "" ] && proto="tcp udp"
	[ "$src" = "vpn" ] && [ -n "$proto" ] && [ -n "$src_dport" ] && [ "$enabled" != "0" ] && [ "$name" != "Allow-DHCP-Request-VPN" ] && {
		for protoi in $proto; do
			checkfw=""
			if [ "$family" = "ipv4" ]; then
				if [ "$src_dip" = "" ] && [ "$src_ip" = "" ]; then
					checkfw=$(echo "$vpsfwlist" | grep "$src_dport	# OMR $username redirect router $src_dport port $protoi")
				else
					comment=""
					[ -n "$src_dip" ] && {
						comment=" to $src_dip"
						if [ ! -f /usr/sbin/nft ]; then
							$IPTABLESSAVE --counters | sed "s:-d $src_dip/32::g" | $IPTABLESRESTORE -w
						else
							rule=$(nft -a list table inet fw4 | grep -m1 "ip daddr $src_dip")
							[ -n "$rule" ] && {
								handle=$(echo $rule | awk '{ print $NF }')
								nft replace rule inet fw4 dstnat_lan handle ${handle} $(echo $rule | awk '{ sub(" comment.*$",""); print }' | sed "s/ip daddr ${src_dip}//") 2>&1 >/dev/null
							}
							rule=$(nft -a list table inet fw4 | grep -m1 "ip daddr $src_dip")
							[ -n "$rule" ] && {
								handle=$(echo $rule | awk '{ print $NF }')
								nft replace rule inet fw4 dstnat_vpn handle $handle $(echo $rule | awk '{ sub(" comment.*$",""); print }' | sed "s/ip daddr ${src_dip}/meta nfproto ipv4/") 2>&1 >/dev/null
							}
						fi
					}
					[ -n "$src_ip" ] && comment=" from $src_ip"
					if [ "$target" = "ACCEPT" ]; then
						checkfw=$(echo "$vpsfwlist" | grep "# OMR $username open router $src_dport port ${protoi}${comment}")
					else
						checkfw=$(echo "$vpsfwlist" | grep "# OMR $username redirect router $src_dport port ${protoi}${comment}")
					fi
				fi
			else
				if [ "$src_dip" = "" ] && [ "$src_ip" = "" ]; then
					if [ "$target" = "ACCEPT" ]; then
						checkfw=$(echo "$vpsfw6list" | grep "$src_dport	# OMR $username open router $src_dport port $protoi")
					else
						checkfw=$(echo "$vpsfw6list" | grep "$src_dport	# OMR $username redirect router $src_dport port $protoi")
					fi
				else
					comment=""
					[ -n "$src_dip" ] && comment=" to $src_dip"
					[ -n "$src_ip" ] && comment=" from $src_ip"
					if [ "$target" = "ACCEPT" ]; then
						checkfw=$(echo "$vpsfw6list" | grep "# OMR $username open router $src_dport port ${protoi}${comment}")
					else
						checkfw=$(echo "$vpsfw6list" | grep "# OMR $username redirect router $src_dport port ${protoi}${comment}")
					fi
				fi
			fi
			if [ "$checkfw" = "" ]; then
				settings='{"name" : "router '$src_dport'","port" : "'$src_dport'","source_dip" : "'$src_dip'","source_ip" : "'$src_ip'","proto" : "'$protoi'","fwtype" : "'$target'","ipproto" : "'$family'"}'
				result=$(_set_json "shorewallopen" "$settings")
			fi
			if [ "$family" = "ipv4" ]; then
				if [ "$src_dip" = "" ] && [ "$src_ip" = "" ]; then
					if [ "$target" = "ACCEPT" ]; then
						vpsfwlist=$(echo "$vpsfwlist" | grep -v "$src_dport	# OMR $username open router $src_dport port $protoi$")
						[ "$username" = "openmptcprouter" ] && vpsfwlist=$(echo "$vpsfwlist" | grep -v "$src_dport	# OMR open router $src_dport port $protoi$")
					else
						vpsfwlist=$(echo "$vpsfwlist" | grep -v "$src_dport	# OMR $username redirect router $src_dport port $protoi$")
						[ "$username" = "openmptcprouter" ] && vpsfwlist=$(echo "$vpsfwlist" | grep -v "$src_dport	# OMR redirect router $src_dport port $protoi$")
					fi
				else
					comment=""
					[ -n "$src_dip" ] && comment=" to $src_dip"
					[ -n "$src_ip" ] && comment=" from $src_ip"
					if [ "$target" = "ACCEPT" ]; then
						vpsfwlist=$(echo "$vpsfwlist" | grep -v "# OMR $username open router $src_dport port ${protoi}${comment}$")
						[ "$username" = "openmptcprouter" ] && vpsfwlist=$(echo "$vpsfwlist" | grep -v "# OMR open router $src_dport port ${protoi}${comment}$")
					else
						vpsfwlist=$(echo "$vpsfwlist" | grep -v "# OMR $username redirect router $src_dport port ${protoi}${comment}")
						[ "$username" = "openmptcprouter" ] && vpsfwlist=$(echo "$vpsfwlist" | grep -v "# OMR redirect router $src_dport port ${protoi}${comment}$")
					fi
				fi
			else
				if [ "$src_dip" = "" ] && [ "$src_ip" = "" ]; then
					if [ "$target" = "ACCEPT" ]; then
						vpsfw6list=$(echo "$vpsfw6list" | grep -v "$src_dport	# OMR $username open router $src_dport port $protoi$")
						[ "$username" = "openmptcprouter" ] && vpsfw6list=$(echo "$vpsfw6list" | grep -v "$src_dport	# OMR open router $src_dport port $protoi$")
					else
						vpsfw6list=$(echo "$vpsfw6list" | grep -v "$src_dport	# OMR $username redirect router $src_dport port $protoi$")
						[ "$username" = "openmptcprouter" ] && vpsfw6list=$(echo "$vpsfw6list" | grep -v "$src_dport	# OMR redirect router $src_dport port $protoi$")
					fi
				else
					[ -n "$src_dip" ] && comment=" to $src_dip"
					[ -n "$src_ip" ] && comment=" from $src_ip"
					if [ "$target" = "ACCEPT" ]; then
						vpsfw6list=$(echo "$vpsfw6list" | grep -v "# OMR $username open router $src_dport port ${protoi}${comment}$")
						[ "$username" = "openmptcprouter" ] && vpsfw6list=$(echo "$vpsfw6list" | grep -v "# OMR open router $src_dport port ${protoi}${comment}$")
					else
						vpsfw6list=$(echo "$vpsfw6list" | grep -v "# OMR $username redirect router $src_dport port ${protoi}${comment}$")
						[ "$username" = "openmptcprouter" ] && vpsfw6list=$(echo "$vpsfw6list" | grep -v "# OMR redirect router $src_dport port ${protoi}${comment}$")
					fi
				fi
			fi

		done
	}
}

_vps_firewall_close_port() {
	[ -n "$vpsfwlist" ] && {
		echo "$vpsfwlist" | while read -r line; do
			[ -n "$line" ] && {
				type=$(echo $line | awk '{print $1}' | tr -d "\n")
				proto=$(echo $line | awk '{print $4}' | tr -d "\n")
				src_dport=$(echo $line | awk '{print $5}' | tr -d "\n")
				source_port=$(echo $line | awk '{print $6}' | tr -d "\n")
				source_dip=$(echo $line | awk '{print $7}' | tr -d "\n")
				comment=$(echo $line | awk -F' --- ' '{print $2}' | tr -d "\n")
				[ "$source_dip" = "#" ] && source_dip=""
				source_ip=$(echo $line | awk '{print $2}' | awk -F ":" '{print $2}' | tr -d "\n")
				if [ "$source_port" = "-" ]; then
					settings='{"name" : "router '$src_dport'","port" : "'$src_dport'","proto" : "'$proto'","fwtype" : "DNAT","source_dip": "'$source_dip'","source_ip": "'$source_ip'","comment" : "'$comment'"}'
				elif [ "$source_ip" != "" ]; then
					settings='{"name" : "router '$src_dport'","port" : "'$src_dport'","proto" : "'$proto'","fwtype" : "DNAT","source_ip": "'$source_ip'","comment" : "'$comment'"}'
				else
					settings='{"name" : "router '$src_dport'","port" : "'$src_dport'","proto" : "'$proto'","fwtype" : "DNAT","comment" : "'$comment'"}'
				fi
				result=$(_set_json "shorewallclose" "$settings")
				[ "$type" = "ACCEPT" ] && {
					destip=$(echo $comment | awk '{print $3}' | awk -F: '{print $1}')
					destport=$(echo $comment | awk '{print $3}' | awk -F: '{print $2}')
					settings='{"name" : "router '$src_dport'","port" : "'$src_dport'","proto" : "'$proto'","destip" : "'$destip'","destport": "'$destport'"}'
					result=$(_set_json "v2rayunredirect" "$settings")
					result=$(_set_json "xrayunredirect" "$settings")
				}
			}
		done
	}
	[ -n "$vpsfw6list" ] && {
		echo "$vpsfw6list" | while read -r line; do
			[ -n "$line" ] && {
				type=$(echo $line | awk '{print $1}' | tr -d "\n")
				proto=$(echo $line | awk '{print $4}' | tr -d "\n")
				src_dport=$(echo $line | awk '{print $5}' | tr -d "\n")
				source_port=$(echo $line | awk '{print $6}' | tr -d "\n")
				source_dip=$(echo $line | awk '{print $7}' | tr -d "\n")
				comment=$(echo $line | awk -F' --- ' '{print $2}' | tr -d "\n")
				[ "$source_dip" = "#" ] && source_dip=""
				source_ip=$(echo $line | awk '{print $2}' | awk -F ":" '{print $2}' | tr -d "\n")
				if [ "$source_port" = "-" ]; then
					settings='{"name" : "router '$src_dport'","port" : "'$src_dport'","proto" : "'$proto'","fwtype" : "DNAT","ipproto" : "ipv6","source_dip": "'$source_dip'","source_ip": "'$source_ip'","comment" : "'$comment'"}'
				elif [ "$source_ip" != "" ]; then
					settings='{"name" : "router '$src_dport'","port" : "'$src_dport'","proto" : "'$proto'","fwtype" : "DNAT","ipproto" : "ipv6","source_dip": "'$source_dip'","source_ip": "'$source_ip'","comment" : "'$comment'"}'
				else
					settings='{"name" : "router '$src_dport'","port" : "'$src_dport'","proto" : "'$proto'","fwtype" : "DNAT","ipproto" : "ipv6","comment" : "'$comment'"}'
				fi
				result=$(_set_json "shorewallclose" "$settings")
				[ "$type" = "ACCEPT" ] && {
					settings='{"name" : "router '$src_dport'","port" : "'$src_dport'","proto" : "'$proto'","comment" : "'$comment'"}'
					result=$(_set_json "v2rayunredirect" "$settings")
					result=$(_set_json "xrayunredirect" "$settings")
				}
			}
		done
	}
}

# 同步本地和VPS防火墙端口规则
# 先修正本机 fw3/iptables 的 VPN 规则，再登录 VPS 拉取当前端口策略，与本地 firewall 配置对齐，最后清理 VPS 多余旧规则并把“待同步”标志清零
# _set_vps_firewall() {
	
# 	logger -t "OMR" "<$FUNCNAME>..."

# 	# 打印当前fw3规则，筛选出含vpn且带目标地址(-d)的规则,按行读取每条规则到变量c
# 	fw3 -q print | grep 'vpn.* -d' |
# 	while IFS=$"\n" read -r c; do
# 		# 先把原规则改成删除规则并执行（删除旧规则)
# 		eval $(echo $c | sed 's/iptables/iptables -w/' | sed 's/-A/-D/') 2>&1 >/dev/null
# 		# 从规则中提取-d后的公网IP
# 		publicip=$(echo $c | awk -F'-d' '{print $2}' | cut -d '/' -f1 | sed 's/ //g')
# 		# 找到与该公网IP对应的GRE接口名和IP
# 		[ -n "$publicip" ] && {
# 			greintf=$(uci show network | grep "Tunnel for $publicip" | cut -d '.' -f2 | tr -d "\n")
# 			[ -n "$greintf" ] && greip=$(uci -q get network.${greintf}.ipaddr)
# 		}
# 		# 没有找到GRE IP,新的规则去除-d和-s限制
# 		if [ -z "$greip" ]; then
# 			newrule=$(echo $c | sed 's/iptables/iptables -w/' | sed -E -e 's/ -d ([^ ])*//' -e 's/ -s ([^ ])*//')
# 		# 找到了GRE IP,把目标地址改为GRE网段
# 		else
# 			newrule=$(echo $c | sed 's/iptables/iptables -w/' | sed -E -e "s/ -d ([^ ])*/ -d ${greip}\/255.255.255.252/" -e 's/ -s ([^ ])*//')
# 		fi
# 		# 尝试删除可能存在的同名新规则,避免重复
# 		eval $(echo $newrule | sed 's/-A/-D/') || true
# 		# 添加新规则
# 		eval $newrule
# 	done

# 	# 读取函数参数1：指定要处理的server section名
# 	fwservername=$1
# 	# 如果传了参数，同步到全局servername
# 	[ -n "$fwservername" ] && servername=$fwservername
# 	# 如果没传参数，使用现有servername
# 	[ -z "$fwservername" ] && fwservername=$servername
# 	# 配置禁止防火墙重定向则直接退出
# 	[ "$(uci -q get openmptcprouter.${fwservername}.nofwredirect)" = "1" ] && logger -t "OMR" "<$FUNCNAME> ${fwservername} nofwredirect! return now..." && return
# 	[ -z "$(uci -q get openmptcprouter.${fwservername}.username)" ] && logger -t "OMR" "<$FUNCNAME> ${fwservername} has no username! return now..."  && return
# 	[ -z "$(uci -q get openmptcprouter.${fwservername}.password)" ] && logger -t "OMR" "<$FUNCNAME> ${fwservername} has no password! return now..." && return
# 	[ -z "$(uci -q get openmptcprouter.${fwservername}.port)" ] && logger -t "OMR" "<$FUNCNAME> ${fwservername} has no port! return now..." && return
	
# 	# 清空token，重新登录
# 	# 为了保证接下来同步防火墙规则这一关键动作的 可靠性 ，不复用可能过期的状态，而是选择每次都重新建立认证会话
# 	token=""
# 	vps_config=""
# 	_login
# 	[ -z "$token" ] && {
# 		[ "$(logread | tail -n 3 | grep -c 'vps token')" -lt 3 ] && logger -t "OMR" "<$FUNCNAME> Can't get ${fwservername} token, try later"
# 		uci -q batch <<-EOF >/dev/null
# 			set openmptcprouter.${fwservername}.admin_error=1
# 		EOF
# 		return
# 	}

# 	# 读取用户名，后续匹配注释规则时用
# 	username="$(uci -q get openmptcprouter.${fwservername}.username)"
# 	# 组装请求：查询VPS上“redirect router”规则
# 	settings='{"name" : "redirect router"}'
# 	# 请求VPS防火墙规则列表
# 	fw_list=$(_set_json "shorewalllist" "$settings")
# 	# 请求失败则退出
# 	[ -z "$fw_list" ] && logger -t "OMR" "<$FUNCNAME> Can't get IPv4 shorewalllist redirect router from VPS! return now..." && return
# 	# 解析并清理空行（IPv4重定向规则）
# 	vpsfwlist=$(echo $fw_list | jsonfilter -q -e '@.list[*]' | sed '/^[[:space:]]*$/d')
# 	# 查询“open router”规则
# 	settings='{"name" : "open router"}'
# 	# 请求列表
# 	fw_list=$(_set_json "shorewalllist" "$settings")
# 	[ -z "$fw_list" ] && logger -t "OMR" "<$FUNCNAME> Can't get IPv4 shorewalllist open router from VPS! return now..." && return
# 	# 如果已有redirect列表, 追加open列表
# 	if [ -n "$vpsfwlist" ]; then
# 		vpsfwlist="${vpsfwlist}"$'\n'"$(echo $fw_list | jsonfilter -q -e '@.list[*]' | sed '/^[[:space:]]*$/d')"
# 	# 没有redirect列表, 直接重新赋值
# 	else
# 		vpsfwlist="$(echo $fw_list | jsonfilter -q -e '@.list[*]' | sed '/^[[:space:]]*$/d')"
# 	fi
# 	# 查询IPv6 redirect规则
# 	settings='{"name" : "redirect router","ipproto" : "ipv6"}'
# 	fw6_list=$(_set_json "shorewalllist" "$settings")
# 	# 失败退出
# 	[ -z "$fw6_list" ] && logger -t "OMR" "<$FUNCNAME> Can't get IPv6 shorewalllist redirect router from VPS! return now..." && return
# 	# 解析IPv6 redirect列表
# 	vpsfw6list=$(echo $fw6_list | jsonfilter -q -e '@.list[*]' | sed '/^[[:space:]]*$/d')
# 	# 查询IPv6 open规则
# 	settings='{"name" : "open router","ipproto" : "ipv6"}'
# 	# 请求IPv6 open列表
# 	fw6_list=$(_set_json "shorewalllist" "$settings")
# 	# 失败退出
# 	[ -z "$fw6_list" ] && logger -t "OMR" "<$FUNCNAME> Can't get IPv6 shorewalllist open router from VPS! return now..." && return
# 	# 若已有IPv6 redirect列表, 追加IPv6 open列表
# 	if [ -n "$vpsfw6list" ]; then
# 		vpsfw6list="$vpsfw6list\n$(echo $fw6_list | jsonfilter -q -e '@.list[*]' | sed '/^[[:space:]]*$/d')"
# 	# 没有IPv6 redirect列表, 直接重新赋值
# 	else
# 		vpsfw6list="$(echo $fw6_list | jsonfilter -q -e '@.list[*]' | sed '/^[[:space:]]*$/d')"
# 	fi
# 	# /etc/config/firewall
# 	config_load firewall
# 	# 遍历redirect段：确保VPS有对应规则，或同步创建
# 	config_foreach _vps_firewall_redirect_port redirect
# 	# 遍历rule段：同样进行同步
# 	config_foreach _vps_firewall_redirect_port rule
# 	# 若VPS仍有未匹配的旧规则（IPv4/IPv6任一非空）, 调用清理函数，删除VPS遗留规则
# 	[ -n "$vpsfwlist" ] || [ -n "$vpsfw6list" ] && {
# 		logger -t "OMR" "<$FUNCNAME> Remove old firewall rules"
# 		_vps_firewall_close_port
# 	}
# 	# 回写状态：防火墙同步动作完成
# 	uci -q batch <<-EOF >/dev/null
# 		set openmptcprouter.${fwservername}.set_firewall=0
# 		commit openmptcprouter
# 	EOF
# }

# set_vps_firewall() {
# 	local server_opt=$2
# 	if [ -n "$server_opt" ]; then
# 		_set_vps_firewall $server_opt
# 	else
# 		config_load openmptcprouter
# 		config_foreach _set_vps_firewall server
# 	fi
# }

_set_openvpn_server() {
	local option=$2
	local value=$3
	if [ "$value" = "true" ]; then
		value=1
	elif [ "$value" = "false" ]; then
		value=0
	fi
	if [ "$(echo $1 | grep omr)" != "" ]; then 
		if [ "$option" = "remote" ]; then
			uci -q delete openvpn.$1.$option
			uci -q add_list openvpn.$1.$option=$value
		else
			uci -q set openvpn.$1.$option=$value
		fi
	fi
}

# 同步VPS配置到本地，更新本地配置
_set_config_from_vps() {

	logger -t "OMR" "<$FUNCNAME>..."

	local shadowsocks_disabled vpn redirect shorewall_redirect openvpn_key
	[ -z "$vps_config" ] && vps_config=$(_get_json "config?serial=${serial}")
	[ -z "$vps_config" ] && return

	logger -t "OMR" "<$FUNCNAME> Get config from server ${servername}..."
	
	noerror=1
	# get VPS ip
	vpsip="$(uci -q get openmptcprouter.${servername}.ip | awk '{print $1}')"
	vps_lastchange="$(echo "$vps_config" | jsonfilter -q -e '@.vps.lastchange')"
	lastchange="$(uci -q get openmptcprouter.${servername}.lastchange)"
	[ -z "$lastchange" ] && lastchange=0
	#[ -n "$lastchange" ] && [ -n "$vps_lastchange" ] && [ "$lastchange" -gt "$vps_lastchange" ] && return

	logger -t "OMR" "<$FUNCNAME> OMR-Tracker..."
	vpsinternet="$(echo "$vps_config" | jsonfilter -q -e '@.network.internet')"
	if [ "$vpsinternet" = "false" ] && [ "$(uci -q get openmptcprouter.settings.external_check)" != "0" ]; then
		uci -q batch <<-EOF >/dev/null
			set openmptcprouter.settings.external_check='0'
		EOF
		logger -t "OMR" "<$FUNCNAME> OMR-Tracker restart"
		/etc/init.d/omr-tracker restart
	fi

	logger -t "OMR" "<$FUNCNAME> ula..."
	ula="$(echo "$vps_config" | jsonfilter -q -e '@.ip6in4.ula')"
	logger -t "OMR" "<$FUNCNAME> ula:${ula}"
	if [ -n "$ula" ] && [[ "$ula" != *" "* ]]; then

		logger -t "OMR" "<$FUNCNAME> ula:${ula}"

		uci -q batch <<-EOF >/dev/null
		set network.globals.ula_prefix=$ula
		EOF
	fi

	# Set current VPN
	logger -t "OMR" "<$FUNCNAME> current_vpn..."
	current_vpn="$(uci -q get openmptcprouter.settings.vpn)"
	logger -t "OMR" "<$FUNCNAME> current_vpn:${current_vpn}"
	if [ -z "$current_vpn" ] || ([ -n "$vps_lastchange" ] && [ "$vps_lastchange" -gt "$lastchange" ]); then
		current_vpn="$(echo "$vps_config" | jsonfilter -q -e '@.vpn.current')"
		if [ -n "$current_vpn" ]; then

			logger -t "OMR" "<$FUNCNAME> Set current VPN ${current_vpn}"

			uci -q batch <<-EOF >/dev/null
			set openmptcprouter.settings.vpn=${current_vpn}
			commit openmptcprouter
			EOF
		fi
	fi

	# OpenVPN settings
	openvpn_key="$(echo "$vps_config" | jsonfilter -q -e '@.openvpn.key')"
	[ -n "$openvpn_key" ] && {
		echo $openvpn_key | base64 -d > /etc/luci-uploads/openvpn.key
		openvpn_port="$(echo "$vps_config" | jsonfilter -q -e '@.openvpn.port')"
		[ -z "$openvpn_port" ] && openvpn_port="65001"
		vpn="$(uci -q get openmptcprouter.settings.vpn)"
		openvpn_state=0
		if [ "$vpn" = "openvpn" ]; then
			openvpn_state=1
		fi
		config_load openvpn
		config_foreach _set_openvpn_server openvpn "port" "$openvpn_port"
		config_foreach _set_openvpn_server openvpn "secret" "/etc/luci-uploads/openvpn.key"

		if [ "$(uci -q get openmptcprouter.settings.openvpn_lb)" = "0" ]; then
			config_foreach _set_openvpn_server openvpn "enabled" "0"
			uci -q set openvpn.omr.enabled=$openvpn_state
		else
			config_foreach _set_openvpn_server openvpn "enabled" "$openvpn_state"
		fi

		if [ "$(uci -q get openvpn.omr.remote)" != "127.0.0.1" ]; then
			config_foreach _set_openvpn_server openvpn "remote" "$vpsip"
			#uci -q set openvpn.omr.remote="$vpsip"
		fi
		if [ -n "$(uci -q changes openvpn)" ]; then
			uci -q commit openvpn
			if [ "$(uci -q get openvpn.omr.enabled)" = "1" ]; then
				logger -t "OMR" "<$FUNCNAME> OpenVPN restart..."
				/etc/init.d/openvpn restart
			fi
		fi
	}
	openvpn_client_key="$(echo "$vps_config" | jsonfilter -q -e '@.openvpn.client_key')"
	[ -n "$openvpn_client_key" ] && {
		echo $openvpn_client_key | base64 -d > /etc/luci-uploads/client.key
	}
	openvpn_client_crt="$(echo "$vps_config" | jsonfilter -q -e '@.openvpn.client_crt')"
	[ -n "$openvpn_client_crt" ] && {
		echo $openvpn_client_crt | base64 -d > /etc/luci-uploads/client.crt
	}
	openvpn_client_ca="$(echo "$vps_config" | jsonfilter -q -e '@.openvpn.client_ca')"
	[ -n "$openvpn_client_ca" ] && {
		echo $openvpn_client_ca | base64 -d > /etc/luci-uploads/ca.crt
	}
	[ -n "$openvpn_client_key" ] && [ -n "$openvpn_client_crt" ] && [ -n "$openvpn_client_ca" ] && {
		openvpn_port="$(echo "$vps_config" | jsonfilter -q -e '@.openvpn.port')"
		[ -z "$openvpn_port" ] && openvpn_port="65001"
		vpn="$(uci -q get openmptcprouter.settings.vpn)"
		openvpn_state=0
		if [ "$vpn" = "openvpn" ]; then
			openvpn_state=1
		fi

		NBCPU=$(grep -c '^processor' /proc/cpuinfo | tr -d "\n")
		if [ "$NBCPU" -gt 1 ] && [ -z "$(uci -q get openvpn.omr2)" ]; then
			[ -f /rom/etc/uci-defaults/2020-omr-vpn ] && ./rom/etc/uci-defaults/2020-omr-vpn
			[ -f /usr/share/omr-update/2020-omr-vpn ] && ./usr/share/omr-update/2020-omr-vpn
		fi

		config_load openvpn
		if [ "$(uci -q get openmptcprouter.settings.openvpn_lb)" = "0" ]; then
			config_foreach _set_openvpn_server openvpn "enabled" "0"
			uci -q set openvpn.omr.enabled=$openvpn_state
		else
			config_foreach _set_openvpn_server openvpn "enabled" "$openvpn_state"
		fi
		config_foreach _set_openvpn_server openvpn "key" "/etc/luci-uploads/client.key"
		config_foreach _set_openvpn_server openvpn "cert" "/etc/luci-uploads/client.crt"
		config_foreach _set_openvpn_server openvpn "ca" "/etc/luci-uploads/ca.crt"
		config_foreach _set_openvpn_server openvpn "tls_client" "1"
		config_foreach _set_openvpn_server openvpn "client" "1"
		config_foreach _set_openvpn_server openvpn "allow_recursive_routing" "1"

		if [ "$(uci -q get openvpn.omr.remote)" != "127.0.0.1" ]; then
			config_foreach _set_openvpn_server openvpn "remote" "$vpsip"
			#uci -q set openvpn.omr.remote="$vpsip"
		fi
		if [ -n "$(uci -q changes openvpn)" ]; then
			uci -q commit openvpn
			if [ "$(uci -q get openvpn.omr.enabled)" = "1" ]; then
				logger -t "OMR" "<$FUNCNAME> OpenVPN restart..."
				/etc/init.d/openvpn restart
			fi
		fi
	}

	# Shorewall settings
	shorewall_redirect="$(echo "$vps_config" | jsonfilter -q -e '@.shorewall.redirect_ports')"
	[ "$shorewall_redirect" = "enable" ] && redirect="1"
	[ "$shorewall_redirect" = "disable" ] && redirect="0"
	uci -q batch <<-EOF >/dev/null
		set openmptcprouter.${servername}.redirect_ports=$redirect
	EOF

	# MPTCP settings
	mptcp_path_manager="$(echo "$vps_config" | jsonfilter -q -e '@.mptcp.path_manager')"
	mptcp_scheduler="$(echo "$vps_config" | jsonfilter -q -e '@.mptcp.scheduler')"
	mptcp_checksum="$(echo "$vps_config" | jsonfilter -q -e '@.mptcp.checksum')"
	mptcp_syn_retries="$(echo "$vps_config" | jsonfilter -q -e '@.mptcp.syn_retries')"
	mptcp_enabled="$(echo "$vps_config" | jsonfilter -q -e '@.mptcp.enabled')"
	if [ "$mptcp_enabled" = "0" ]; then
		mptcp_enabled="disable"
	else
		mptcp_enabled="enable"
	fi
	congestion="$(echo "$vps_config" | jsonfilter -q -e '@.network.congestion_control')"
	uci -q batch <<-EOF >/dev/null
		set network.globals.multipath=$mptcp_enabled
		set network.globals.mptcp_checksum=$mptcp_checksum
		set network.globals.congestion=$congestion
		commit network
	EOF
	if [ "$mptcp_path_manager" != "" ] && [ "$mptcp_scheduler" != "" ] && [ "$mptcp_syn_retries" != "" ]; then
		uci -q batch <<-EOF >/dev/null
			set network.globals.mptcp_path_manager=$mptcp_path_manager
			set network.globals.mptcp_scheduler=$mptcp_scheduler
			set network.globals.mptcp_syn_retries=$mptcp_syn_retries
			commit network
		EOF
	fi

	# Check if server get an IPv6, if not disable IPv6 on OMR
	vps_ipv6_addr="$(echo "$vps_config" | jsonfilter -q -e '@.network.ipv6')"
	if [ -z "$vps_ipv6_addr" ]; then
		if [ "$(uci -q get openmptcprouter.settings.disable_ipv6)" = "0" ]; then
			logger -t "OMR" "<$FUNCNAME> No IPv6 support on VPS side ?"
		fi

	else
		uci -q batch <<-EOF >/dev/null
			set openmptcprouter.${servername}.ipv6=$vps_ipv6_addr
		EOF
	fi

	omr6in4_vps_localip="$(echo "$vps_config" | jsonfilter -q -e '@.ip6in4.localip')"
	omr6in4_vps_remoteip="$(echo "$vps_config" | jsonfilter -q -e '@.ip6in4.remoteip')"
	if ([ -n "$omr6in4_vps_localip" ] && [ "$omr6in4_vps_localip" != "$(uci -q get network.omr6in4.gateway)" ]) || ([ -n "$omr6in4_vps_remoteip" ] && [ "$omr6in4_vps_remoteip" != "$(uci -q get network.omr6in4.ip6addr)" ]); then
		logger -t "OMR" "<$FUNCNAME> Set omr6in4 ip address and gateway"
		uci -q batch <<-EOF >/dev/null
			set network.omr6in4.ip6addr="$omr6in4_vps_remoteip"
			set network.omr6in4.gateway="$omr6in4_vps_localip"
		EOF
		if [ -n "$(uci -q changes network)" ]; then
			uci -q commit network
			/etc/init.d/network reload
			sleep 6
		fi
	fi

	# Get VPS iperf config
	iperf_user="$(echo "$vps_config" | jsonfilter -q -e '@.iperf.user')"
	iperf_pass="$(echo "$vps_config" | jsonfilter -q -e '@.iperf.password')"
	iperf_key="$(echo "$vps_config" | jsonfilter -q -e '@.iperf.key')"
	uci -q batch <<-EOF >/dev/null
		del iperf.${servername}
		set iperf.${servername}=server
		set iperf.${servername}.host=$server
		set iperf.${servername}.ports=65400
		set iperf.${servername}.ipv4=1
		set iperf.${servername}.ipv6=0
		set iperf.${servername}.speed=1000
		set iperf.${servername}.tcp=1
		set iperf.${servername}.udp=1
		set iperf.${servername}.user=$iperf_user
		set iperf.${servername}.password=$iperf_pass
		set iperf.${servername}.key="$iperf_key"
		commit iperf
	EOF

	# Get available server
	available_vpn="$(echo "$vps_config" | jsonfilter -q -e '@.vpn.available' | sed -e 's/\[ //' -e 's/ \]//' -e 's/,//g')"
	available_proxy="$(echo "$vps_config" | jsonfilter -q -e '@.proxy.available' | sed -e 's/\[ //' -e 's/ \]//' -e 's/,//g')"
	uci -q batch <<-EOF >/dev/null
		del openmptcprouter.${servername}.available_vpn
		del openmptcprouter.${servername}.available_proxy
	EOF

	if [ -n "$available_vpn" ]; then
		for vpn in $available_vpn; do
			uci -q batch <<-EOF >/dev/null
				add_list openmptcprouter.${servername}.available_vpn=$vpn
			EOF
		done
	fi
	if [ -n "$available_proxy" ]; then
		for proxy in $available_proxy; do
			uci -q batch <<-EOF >/dev/null
				add_list openmptcprouter.${servername}.available_proxy=$proxy
			EOF
		done
	fi

	if [ "$noerror" = "1" ]; then
		uci -q batch <<-EOF >/dev/null
			set openmptcprouter.${servername}.get_config=0
			commit openmptcprouter
		EOF
	fi
}

_backup_send() {
	servername=$1
	[ -z "$(uci -q get openmptcprouter.${servername}.username)" ] && return
	[ -z "$(uci -q get openmptcprouter.${servername}.password)" ] && return
	[ -z "$(uci -q get openmptcprouter.${servername}.port)" ] && return
	token=""
	vps_config=""
	_login
	[ -z "$token" ] && {
		[ "$(logread | tail -n 3 | grep -c 'vps token')" -lt 3 ] && logger -t "OMR" "Can't get ${servername} token, try later"
		uci -q batch <<-EOF >/dev/null
			set openmptcprouter.${servername}.admin_error=1
		EOF
		return
	}
	sysupgrade -k -b /tmp/backup.tar.gz
	backup_data="$(cat /tmp/backup.tar.gz | base64 | tr -d '\n')"
	backup_sha256sum="$(sha256sum /tmp/backup.tar.gz | awk '{print $1}')"
	[ -n "$backup_data" ] && {
		logger -t "OMR" "<$FUNCNAME> Send backup file to server $servername"
		local backupjson
		backupjson='{"data": "'$backup_data'","sha256sum": "'$backup_sha256sum'"}'
		echo "$backupjson" > /tmp/backupjson
		result=$(_set_json "backuppost" "@/tmp/backupjson")
		rm -f /tmp/backupjson
		uci -q set openmptcprouter.$servername.lastbackup=$(date +%s)
	}
}

backup_send() {
	config_load openmptcprouter
	config_foreach _backup_send server
}


_backup_get() {
	servername=$1
	[ -z "$(uci -q get openmptcprouter.${servername}.username)" ] && return
	[ -z "$(uci -q get openmptcprouter.${servername}.password)" ] && return
	[ -z "$(uci -q get openmptcprouter.${servername}.port)" ] && return
	[ -z "$lastbackup" ] || [ "$lastbackup" -lt "$(uci -q get openmptcprouter.$servername.lastbackup)" ] && {
		lastbackup="$(uci -q get openmptcprouter.$servername.lastbackup)"
		serverbackup="$servername"
	}
}

_backup_get_and_apply() {
	servername=$1
	backupfile=$2
	token=""
	vps_config=""
	_login
	[ -z "$token" ] && {
		[ "$(logread | tail -n 3 | grep -c 'vps token')" -lt 3 ] && logger -t "OMR" "<$FUNCNAME> Can't get ${servername} token, try later"
		uci -q batch <<-EOF >/dev/null
			set openmptcprouter.${servername}.admin_error=1
		EOF
		return
	}
	if [ -n "$backupfile" ]; then
		echo "get $backupfile"
		vps_backup=$(_get_json "backupget?filename=${backupfile}")
	else
		vps_backup=$(_get_json "backupget")
	fi
	[ -z "$vps_backup" ] && return
	backup_data="$(echo "$vps_backup" | jsonfilter -q -e '@.data')"
	backup_sha256sum="$(echo "$vps_backup" | jsonfilter -q -e '@.sha256sum')"
	[ -n "$backup_data" ] && {
		echo $backup_data | base64 -d > /tmp/backup.tar.gz
		sysupgrade -r /tmp/backup.tar.gz
	}
}

backup_get() {
	backuptoapply=$2
	if [ -n "$backuptoapply" ]; then
		_backup_get_and_apply $1 $2
	else
		lastbackup=""
		serverbackup=""
		config_load openmptcprouter
		config_foreach _backup_get server
		[ -n "$serverbackup" ] && _backup_get_and_apply $serverbackup
	fi
}

# 从VPS获取备份配置
# _backup_list() {

# 	logger -t "OMR" "<$FUNCNAME>..."

# 	bservername=$1
# 	[ -z "$servername" ] && servername=$bservername
# 	[ -z "$(uci -q get openmptcprouter.${servername}.username)" ] && return
# 	[ -z "$(uci -q get openmptcprouter.${servername}.password)" ] && return
# 	[ -z "$(uci -q get openmptcprouter.${servername}.port)" ] && return
# 	token=""
# 	vps_config=""
# 	_login
# 	[ -z "$token" ] && {
# 		[ "$(logread | tail -n 3 | grep -c 'vps token')" -lt 3 ] && logger -t "OMR" "<$FUNCNAME> Can't get ${servername} token, try later"
# 		uci -q batch <<-EOF >/dev/null
# 			set openmptcprouter.${servername}.admin_error=1
# 		EOF
# 		return
# 	}
# 	vps_backup=$(_get_json "backuplist")
# 	[ -z "$vps_backup" ] && logger -t "OMR" "<$FUNCNAME> Have no backuplist" && return
# 	backup_lastmodif="$(echo "$vps_backup" | jsonfilter -q -e '@.modif')"
# 	[ -n "$backup_lastmodif" ] && {
# 		uci -q set openmptcprouter.$servername.lastbackup=$backup_lastmodif
# 		backup_all="$(echo "$vps_backup" | jsonfilter -q -e '@.sorted[*]')"
# 		uci -q del openmptcprouter.$servername.allbackup
# 		echo "$vps_backup" | jsonfilter -q -e '@.sorted[*]' | while read backup; do
# 			name=$(echo "$backup" | jsonfilter -q -e '@[0]' | tr -d '\n')
# 			modiftime=$(echo "$backup" | jsonfilter -q -e '@[1]' | tr -d '\n')
# 			uci -q add_list openmptcprouter.$servername.allbackup="${name}|${modiftime}"
# 		done
# 	}
# }

# backup_list() {
# 	config_load openmptcprouter
# 	config_foreach _backup_list server
# 	[ -n "$(uci -q changes openmptcprouter)" ] && uci -q commit openmptcprouter
# }

# 获取http token
_get_token() {
	servername=$1
	# uci get openmptcprouter.vps.username
	[ -z "$(uci -q get openmptcprouter.${servername}.username)" ] && logger -t "OMR" "<$FUNCNAME> ${servername}.username is empty! return now..." && return		# uci get openmptcprouter.vps.username
	# uci get openmptcprouter.vps.password
	# [ -z "$(uci -q get openmptcprouter.${servername}.password)" ] && return
	# uci get openmptcprouter.vps.port
	[ -z "$(uci -q get openmptcprouter.${servername}.port)" ] && logger -t "OMR" "<$FUNCNAME> ${servername}.port is empty! return now..." && return
	# uci get openmptcprouter.vps.ip
	[ -z "$(uci -q get openmptcprouter.${servername}.ip)" ] && logger -t "OMR" "<$FUNCNAME> ${servername}.username is ip! return now..." && return
	# uci get openmptcprouter.vps.disabled
	# [ "$(uci -q get openmptcprouter.${servername}.disabled)" = "1" ] && return
	token=""
	# 认证登录
	_login
	if [ -z "$token" ]; then
		reason=""
		test_ping() {
			_ping_server $1
			status=$?
			if $(exit $status); then
				reason="can ping server ${servername} on $1"
			else
				reason="can't ping server ${servername} on $1"
			fi
		}
		config_list_foreach "${servername}" ip test_ping
		# uci -q get openmptcprouter.vps.port
		port="$(uci -q get openmptcprouter.${servername}.port)"
		# 测试后台服务是否存在
		api_test() {
			server="$1"
			resolve="$(resolveip -t 5 $server)"
			valid_ip6=$(valid_subnet6 $server)
			if [ "$resolve" != "$server" ] || [ "$valid_ip6" != "ok" ]; then
				if [ "$(curl -s -k -m 3 https://${server}:${port}/)" = "" ]; then
					reason="$reason, no server API answer on $1"
				else
					reason="$reason, server API answer on $1"
				fi
			else
				if [ "$(curl -s -k -m 3 https://[${server}]:${port}/)" = "" ]; then
					reason="$reason, no server API answer on $1"
				else
					reason="$reason, server API answer on $1"
				fi
			fi
		}
		config_list_foreach "${servername}" ip api_test
		
		# uci -q get openmptcprouter.vps.username
		if [ "$(uci -q get openmptcprouter.${servername}.username)" != "openmptcprouter" ]; then
			reason="$reason, custom username"
		fi
		[ "$(logread | tail -n 3 | grep -c 'vps token')" -lt 3 ] && logger -t "OMR" "<$FUNCNAME> Can't get ${servername} token, try later ($reason)"
		uci -q batch <<-EOF >/dev/null
			set openmptcprouter.${servername}.admin_error=1
		EOF
	else
		uci -q batch <<-EOF >/dev/null
			set openmptcprouter.${servername}.token_error=0
			commit openmptcprouter
		EOF
	fi
	echo "$server:$serverport:$token"
}

token() {
	config_load openmptcprouter
	config_foreach _get_token server
}

# 聚合模式
mode_aggregate() {
	if [ -f /usr/lib/openmptcprouter-vps/mode_aggregate.sh ]; then
		. /usr/lib/openmptcprouter-vps/mode_aggregate.sh
	fi

	# 启动聚合模式
	if type mode_aggregate_handler >/dev/null 2>&1; then
		mode_aggregate_handler
		return
	fi
}

# 负载均衡模式
mode_balance() {
	if [ -f /usr/lib/openmptcprouter-vps/mode_balance.sh ]; then
		. /usr/lib/openmptcprouter-vps/mode_balance.sh
	fi

	# 启动聚合模式
	if type mode_balance_handler >/dev/null 2>&1; then
		mode_balance_handler
		return
	fi
}

# 单卡模式
mode_single() {
	
	logger -t "OMR" "<$FUNCNAME> mode: single"

	# 单卡模式逻辑在单独的文件中实现
	if [ -f /usr/lib/openmptcprouter-vps/mode_single.sh ]; then
		. /usr/lib/openmptcprouter-vps/mode_single.sh
	fi
	
	# 单卡模式入口函数
	if type mode_single_handler >/dev/null 2>&1; then
		mode_single_handler
		return
	fi
}

# 工作模式: 单卡模式 / 聚合模式 / 负载均衡模式
work_mode() {
	local mode="$(uci -q get global.global.mode)"
	logger -t "OMR" "<$FUNCNAME> mode: ${mode}"
	case "$mode" in
		'single')
			mode_single
			;;
		'aggregate')
			mode_aggregate
			;;
		'balance')
			mode_balance
			;;
		*)
			logger -t "OMR" "<$FUNCNAME> unknown mode:${mode}! reset to mode single"
			mode_single
			;;
	esac
}

# 服务入口
start_service() {

	logger -t "OMR" "####################################"
	logger -t "OMR" "<$FUNCNAME>..."
	logger -t "OMR" "####################################"

	# WAN口IP
	wanips=""
	
	# 序列号,使用CPU序列号作为整机序列号
	serial=$(cat /proc/cpuinfo | grep Serial | awk '{print $3}')
	logger -t "OMR" "<$FUNCNAME> serial: ${serial}"
	# 记录序列号到/etc/config/openmptcprouter
	local saved_serial="$(uci -q get openmptcprouter.settings.serial)"
	if [ "$saved_serial" != "$serial" ]; then
		uci -q set openmptcprouter.settings.serial="$serial"
		logger -t "OMR" "<$FUNCNAME> serial changed from ${saved_serial} to ${serial}"
	fi

	# 工作模式管理: 单卡模式 / 聚合模式 / 负载均衡模式
	work_mode

	# 系统启动时自动恢复备份的 overlay 层软件包
	if [ "$(ps w | grep sysupgrade)" = "" ]; then
		logger -t "OMR" "<$FUNCNAME> Restart /etc/init.d/sysupgrade..."
		/etc/init.d/sysupgrade restart
	fi
}

# 服务触发器，当相关服务或配置发生变化时，OpenMPTCPRouter的VPS组件能够适当地响应
service_triggers() {
	# 当如下服务发生reload时, 会自动触发当前服务的reload
	logger -t "OMR" "<$FUNCNAME> restart triggered by openvpn"
	procd_add_reload_trigger openvpn
	# 当工作模式发生变化时, 自动触发当前服务的work_mode, 这一行似乎没有正常工作
	# procd_add_config_trigger "config.change" "global" /etc/init.d/openmptcprouter-vps work_mode

	# 当防火墙配置/etc/config/firewall发生变化时，会调用set_vps_firewall
	# procd_add_config_trigger "config.change" "firewall" /etc/init.d/openmptcprouter-vps set_vps_firewall
}
