#!/bin/sh /etc/rc.common
# shellcheck disable=SC2039
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

# 使用procd为每个SIM模组创建一个tracker进程实例

{
	START=90
	USE_PROCD=1
}

. /lib/functions.sh

# 每个sim卡都创建一个procd实例
sim_instance() {
	local enabled sysfs ttyUSB ifname="$1"

	procd_open_instance "$1"
	procd_set_param command /bin/tracker-sim "$1"
	procd_set_param respawn 0 10 0
	procd_set_param stderr 1
	procd_close_instance
}

start_service() {
	config_load sim
	config_foreach sim_instance sim
}

service_triggers() {
	procd_add_reload_trigger sim
}

reload_service() {
	start
}
